apiVersion: v1
kind: Service
metadata:
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
  labels:
    app: ftps
spec:
  type: LoadBalancer
  selector:
    app: ftps
  ports:
  - name: ftp-data
    port: 20
    protocol: TCP
  - name: ftp-control
    port: 21
    protocol: TCP
  - name: passive-1
    port: 30000
    protocol: TCP
  - name: passive-2
    port: 30001
    protocol: TCP
  - name: passive-3
    port: 30002
    protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps
  labels:
    app: ftps
spec:
  selector:
    matchLabels:
      app: ftps
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ftps
    spec:
      serviceAccount: tvan-cit
      containers:
      - name: ftps
        image: ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 20
          name: ftp-data
        - containerPort: 21
          name: ftp-control
        - containerPort: 30000
          name: passive-1
        - containerPort: 30001
          name: passive-2
        - containerPort: 30002
          name: passive-3
